### ISSUE TITLE
add on wp.org

### ISSUE THREAD

**Issue by ttodua** [bekarice/woocommerce-gateway-offline#4]
would be nice if you put this on wp.org official plugins repo, where we can find this easily.

**Comment by jchrislemmer** [comment]
This plugin hasn't been updated in years, I doubt they'll do this.

Also, there won't really be changes to offline payment gateways, so no need really to update it.

**Comment by ttodua** [comment]
no, it will be updated besides of changes - you have to update one character in your plugin once in a while - the version number. SO, even plugin is old, it will be updated several times in the year to change the version number. so, worth to put this on wp.org to be findable.

**Comment by jchrislemmer** [comment]
Haha, okay, If you think so. ;-)

**Comment by ttodua** [comment]
i think all plugins should be put on wp.org so people will find them.

**Comment by bekarice** [comment]
thanks for the feedback all! this plugin is meant more as a code example for other developers, so it's not something I offer support for and don't plan to put on wp.org as a result — I only add plugins there I'm willing to support / maintain.
